### ISSUE TITLE
What does the blue curve in chart.forward(.) represent during the training period?

### ISSUE THREAD

**Issue by QuantDevHacks** [braverock/quantstrat#101]
This isn't quite as urgent as #100, but it would be helpful if I could explain it to my class.  When generating the `chart.forward(.)` plot for a three-year train/one-year test WFA run over three years, the blue curve for the first three years starts at a positive equity value, when the strategy itself starts with a position of zero in the market.  This is more curious given that that gray curves over the same period all start at zero positions.  Should we perhaps just ignore this part of the graph, and just use the blue curve vs gray curves visual analysis over each of the OOS test periods?  Or, is there some other way to explain this?

The image is attached here.  The repro is given below.  Thanks in advance.

![WFA](https://user-images.githubusercontent.com/3461284/57991238-65835400-7a62-11e9-9d5f-c32abcabf194.png)

```
library(quantstrat)

stock.st = c("SPY")
currency("USD")
stock(stock.st, currency="USD",multiplier=1)
Sys.setenv(TZ="UTC") 
initDate = '2011-12-31'
startDate = '2012-01-01'
endDate = '2017-12-31'    
initEq=1e6
tradeSize = initEq/10
getSymbols(stock.st,from=startDate,to=endDate,index.class="POSIXct",adjust=T)

strat.st <- "bbands"
suppressWarnings(rm.strat(strat.st))
strategy(strat.st, store=TRUE)

add.indicator(strat.st, name = "BBands",
              arguments = list(HLC = quote(HLC(mktdata)), maType='SMA'), label='BBands')

add.signal(strat.st, name="sigCrossover",
           arguments=list(columns=c("Close","up"),relationship="gt"),
           label="Cl.gt.UpperBand")

add.signal(strat.st, name="sigCrossover",
           arguments=list(columns=c("Close","dn"),relationship="lt"),
           label="Cl.lt.LowerBand")

add.signal(strat.st, name="sigCrossover",
           arguments=list(columns=c("High","Low","mavg"),relationship="op"),
           label="Cross.Mid")

add.rule(strategy = strat.st, name='ruleSignal',
         arguments=list(sigcol="Cl.gt.UpperBand",sigval=TRUE, orderqty=-100,
                        ordertype='market', orderside=NULL, threshold=NULL),
         type='enter', label = "Enter.Short")

add.rule(strategy = strat.st, name='ruleSignal',
         arguments=list(sigcol="Cl.lt.LowerBand",sigval=TRUE, orderqty=100,
                        ordertype='market', orderside=NULL, threshold=NULL),
         type='enter', label = "Enter.Long")

add.rule(strategy = strat.st, name='ruleSignal',
         arguments=list(sigcol="Cross.Mid",sigval=TRUE, orderqty= 'all',
                        ordertype='market', orderside=NULL, threshold=NULL),
         type='exit', label = "Exit.All")

add.distribution(strat.st,
                 paramset.label = 'BBOPT',
                 component.type = 'indicator',
                 component.label = 'BBands',
                 variable = list(n = seq(10,30,by=10)),     # 2 steps total
                 label = 'n'
)

add.distribution(strat.st,
                 paramset.label = 'BBOPT',
                 component.type = 'indicator',
                 component.label = 'BBands',
                 variable = list(sd = seq(1,3,by=1)),    # 2 steps total
                 label = 'sd'
)

suppressWarnings(rm.strat("opt"))
initPortf(name="opt", stock.st, initDate=initDate)
initAcct(name="opt", portfolios="opt",
         initDate=initDate, initEq=initEq)
initOrders(portfolio="opt", initDate=initDate)

# These will also be used after running WFA, so 
# define once here:
yrsTrain <- 3     
yrsTest <- 1

results <- walk.forward(
  strategy.st=strat.st,
  paramset.label='BBOPT',
  portfolio.st="opt",
  account.st="opt",
  period='years',
  k.training=yrsTrain,
  k.testing=yrsTest,
  nsamples=0,
  audit.prefix='wfa',
  anchored=FALSE,
  verbose=TRUE,
  savewf=TRUE
)

# Now, we look at a plot of each of the OOS test periods using the
# respective optimization in each in-sample training periods.
# What is not clear, however, is what the blue curve in the training
# period represents: a) which training period optimization period it
# represents (or is it something else), and b) why does it start from
# a nonzero position at the outset?
chart.forward(results)  # 'results' is the output *R environment* from
                        # the walk.forward(.) function call above.

```

**Comment by jaymon0703** [comment]
Hi @QuantDevHacks, using the current 102_walk.forward branch in quantstrat, running your script above and calling `chart.forward("wfa.SPY.20140102T000000.20161230T000000.Results.RData")` i get the below chart output. The blue line is simply the mean PnL of all simulations as at the start of the first OOS test window (Jan-2015 in your case). The reasoning for adding the mean cumsum PnL of all suimulations until that date is because they would have had a head start compared with the OOS portfolio which only starts in Jan-2015. So as opposed to having the blue line start from zero in Jan-2015 and distorting the visual performance of the OOS portfolio, we true up the OOS portfolio at that date.

![image](https://user-images.githubusercontent.com/4340156/58151506-258ebd80-7c6a-11e9-82c0-9b665009b6a4.png)

**Comment by jaymon0703** [comment]
hi @QuantDevHacks if you are happy with the above explanation feel free to close the issue?

**Comment by jaymon0703** [comment]
Hi @QuantDevHacks, i have finally gotten to adding this repro code as a demo and added a test on the back of it, which runs with `R CMD check` so we can catch issues before any breaking code is committed. Thanks again for the repro and the report.

https://github.com/braverock/quantstrat/commit/dd608a74c8dfbcedd2af0c3df3518050cdd52725
