### ISSUE TITLE
R session aborted

### ISSUE THREAD

**Issue by PlanNoa** [braverock/quantstrat#106]
when I try ```applyIndicators()```, I got 'R Session Aborted. R encountered a fatal error. The session was terminated.'

This is my full code:
```R
initDate = "1990-01-01"
from = "2003-01-01"
to = "2013-12-31"
options(width = 70)

source("demoData.R")

tradeSize <- 10000
initEq <- tradeSize * length(symbols)

strategy.st <- "Clenow_Simple"
portfolio.st <- "Clenow_Simple"
account.st <- "Clenow_Simple"
rm.strat(portfolio.st)
rm.strat(strategy.st)

initPortf(portfolio.st, symbols = symbols, initDate = initDate, currency = 'USD')

initAcct(account.st, portfolios = portfolio.st, 
        initDate = initDate, currency = 'USD', initEq = initEq)

initOrders(portfolio.st, initDate = initDate)

strategy(strategy.st, store = TRUE)

nLag = 252
pctATR = 0.02
period = 10

namedLag <- function(x, k = 1, na.pad = TRUE, ...) {
  out <- lag(x, k = k, na.pad = na.pad, ...)
  out[is.na(out)] <- x[is.na(out)]
  colnames(out) <- "namedLag"
  return(out)
}

add.indicator(strategy.st, name = "namedLag",
  arguments = list(x = quote(Cl(mktdata)), k = nLag),
  label = "ind")

add.indicator(strategy.st, name = "lagATR",
  arguments = list(HLC = quote(HLC(mktdata)), n = period),
  label = "atrX")

test <- applyIndicators(strategy.st, mktdata = OHLC(XLB)) # error occered.
```
I'm using Rstudio and R 3.6.0.

**Comment by jaymon0703** [comment]
Hi @PlanNoa if you send me your demo dataset i will see if i can reproduce the issue, and hopefully advise further. If this is an option, you can send your dataset to jaymon0703 at gmail dot com. Thanks.

**Comment by jaymon0703** [comment]
Hi @PlanNoa thanks for the dataset. Where do you source the lagATR function, is that in a separate package or is that defined elsewhere?

**Comment by PlanNoa** [comment]
Hi @jaymon0703 actually I'm studying with book 'Quantitative trading with R'. I think you will able to see all source code in [here](https://github.com/hgeorgako/rfortraders/blob/master/Chapter_07/code.R):  lagATR function is in line 64, thank.

**Comment by PlanNoa** [comment]
Also I got same error in line 230 and 251.

**Comment by joshuaulrich** [comment]
Hi @PlanNoa, can you provide the output from `sessionInfo()`?

> Also I got same error in line 230 and 251.

What error?  What file are those lines in?

**Comment by jaymon0703** [comment]
Thanks @PlanNoa, but i am unable to reproduce your issue and instead get the indicators computed as expected. See below screenshot:

![image](https://user-images.githubusercontent.com/4340156/63210115-5e63f480-c0ea-11e9-89c8-42714d7db1a0.png)

A few of us are taking a look...if you can provide output from sessionInfo() that might help. 

@joshuaulrich see https://github.com/hgeorgako/rfortraders/blob/master/Chapter_07/code.R for the source code @PlanNoa is referring to.

**Comment by PlanNoa** [comment]
Thank you for helping me. I tried this in all-new virtual environment, and it succeeded.

**Comment by jaymon0703** [comment]
Good to hear. Thanks for closing the issue.
