### ISSUE TITLE
code inside a function

### ISSUE THREAD

**Issue by helgasoft** [braverock/quantstrat#109]
Using _blotter_ in Shiny works. Now we want to expand to _quantstrat_ and wrap code in functions. Here is the problem:
```
url <- 'https://raw.githubusercontent.com/braverock/quantstrat/master/demo/bbands.R'
source(url)         # works fine standalone
rm(list = setdiff(ls(), 'url'))
tlines <- scan(url, "character", sep='\n')
tlines <- c('f<-function() {', tlines, '}; f()')    # now wrap same code in a function
source(expr=parse(text=tlines))     # error
# Error in get(symbol, envir = envir) : object 'IBM' not found
```
The problem comes from environment handling inside quantstrat. If _mdenv=environment()_ is added to _applyStrategy_, the IBM data is found, but then _updatePortf_ cannot locate it. Also - _applyStrategy_ creates _mktdata_ in the global environment (?!).
Is quantstrat code standalone only? Or is there an easy solution we overlooked?

**Comment by braverock** [comment]
This is not a reproducible example, and looks like a bug in your code, not quantstrat.

I think you will need to specify your environments everywhere.  All blotter and quantstrat functions allow you to specify environments, so if you plan to wrap things in enclosing functions, you need to manage the environments where you are storing things.

**Comment by braverock** [comment]
@helgasoft also note that even inside a Shiny function, you can wrap an expression in `eval` to force evaluation in a specific enclosing environment rather than whatever environment (like the function environment) that your calling code is running from.
