### ISSUE TITLE
Traded prices are not falling within OHLC 

### ISSUE THREAD

**Issue by kvekka** [braverock/quantstrat#113]
In the code, attached herein, I have found that the price at which the sale of the stock occurs does not fall within the OHLC prices for that day. A different price is captured for sale resulting in erroneous trading and results. 

I've analyzed the results from mktdata and orderbook and have found these discrepancies in the price. The stocks are being bought at appropriate prices but, they are not being sold at appropriate prices. 

In my example, SPY is being investigated here for the period from 2017-01-01 to 2018-12-31.
From orderbook, first buy occurs on 18-04-2017: 44 stocks @226.7125; From mktdata, 226.7125 lies in the range of high - 226.7125 - and low - 225.3493. So, this is fine. 

These are being triggered for sale on 17-05-2017.
From orderbook, on 17-05-2017, all stocks @235.9783; On this day, values observed are as follows: high - 232.1171 - and low - 227.9307.  This price is not within the High, and Low band. 
On 18-05-2017, values observed are as follows: high - 229.8644 - and low - 227.6213. Here the sale price does not fall between the range between High and Low. 

It seems that it is capturing price from some other column, "Slab_Price".

Is there a way to make it capture the correct trade prices?
Code for the program is attached here. [price_diff_error.txt](https://github.com/braverock/quantstrat/files/3797122/price_diff_error.txt)

**Comment by braverock** [comment]
I get columns:

           SPY.Open SPY.High  SPY.Low SPY.Close SPY.Volume SPY.Adjusted

from getSymbols.

'Slab_Price' is one of your indicators.  You might also want to take out the word 'Price' from this indicator.

Alternately, you probably need a 'prefer' argument.  

see ?getPrice

As documented, quantstrat calls `getPrice` to figure out what valid prices exist, and then chooses a trade price from the returned list.  You can test this by using getPrice on your data outside of quantstrat.

If the call to getPrice returns multiple columns, the first will be used.

Also note that market orders on OHLC data will be executed one period after the signal, not on the same period as the signal.

**Comment by kvekka** [comment]
@braverock  Thank you, your suggestion does solve the issue. 

Would you be knowing any timestamp based example?

**Comment by jaymon0703** [comment]
Hi @kvekka to add to @braverock's comment, `getPrice()` is a function inside `quantmod` and if getPrice(x) is called for a rule without a `prefer` argument specified it will check for 3 price columns in x=mktdata in this order: "has.Price()", "has.Trade()" and "has.Cl()". In your example because there was a column name "Slab_Price" the grep returned that column as the price to use for the exit.

We are thinking of making this a bit more explicit in the docs for the prefer param in the docs for `ruleSignal`.

Below the getPrice() function from quantmod for reference:
```r

function (x, symbol = NULL, prefer = NULL, ...) 
{
  if (!is.null(symbol)) {
    loc <- grep(symbol, colnames(x))
    if (!identical(loc, integer(0))) {
      x <- x[, loc]
    }
    else {
      stop(paste("subscript out of bounds: no column name containing", 
        symbol))
    }
  }
  if (is.null(prefer)) {
    if (has.Price(x)) 
      prefer = "price"
    else if (has.Trade(x)) 
      prefer = "trade"
    else if (has.Cl(x)) 
      prefer = "close"
    else stop("subscript out of bounds, no price was discernible from the data")
  }
  if (!is.null(prefer)) {
    loc <- NULL
    switch(prefer, Op = , open = , Open = {
      loc <- has.Op(x, which = TRUE)
    }, Hi = , high = , High = {
      loc <- has.Hi(x, which = TRUE)
    }, Lo = , low = , Low = {
      loc <- has.Lo(x, which = TRUE)
    }, Cl = , close = , Close = {
      loc <- has.Cl(x, which = TRUE)
    }, Bid = , bid = {
      loc <- has.Bid(x, which = TRUE)
    }, Ask = , ask = , Offer = , offer = {
      loc <- has.Ask(x, which = TRUE)
    }, Mid = , mid = , Midpoint = , midpoint = {
      loc <- has.Mid(x, which = TRUE)
    }, Trade = , trade = {
      loc <- has.Trade(x, which = TRUE)
    }, Price = , price = {
      loc <- has.Price(x, which = TRUE)
    }, {
      loc <- grep(prefer, colnames(x))
    })
    if (!identical(loc, integer(0))) 
      return(x[, loc])
    else stop("subscript out of bounds, no price was discernible from the data")
  }
}

```

**Comment by kvekka** [comment]
Thank you again. This explains the discrepancy observed.
