### ISSUE TITLE
Problems with cygwin installing blotter

### ISSUE THREAD

**Issue by gradinv** [braverock/quantstrat#128]
Output error:

* installing *source* package 'blotter' ...
** using staged installation
** libs

*** arch - i386
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c calcPosAvgCost.c -o calcPosAvgCost.o
      2 [main] sh (12408) C:\RBuildTools\3.5\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x612A5410/0x11F5410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
make: *** [C:/PROGRA~1/R/R-36~1.1/etc/i386/Makeconf:208: calcPosAvgCost.o] Error 127
ERROR: compilation failed for package 'blotter'
* removing 'C:/Users/1/Documents/R/win-library/3.6/blotter'
Ошибка: Failed to install 'blotter' from GitHub:
  (конвертировано из предупреждения) installation of package ‘C:/Users/1/AppData/Local/Temp/RtmpuwRecu/file21146230729/blotter_0.15.0.tar.gz’ had non-zero exit status

**Comment by braverock** [comment]
The current version of R is 4.0.3.

You are using a version of Rtools installed under R 3.5, and trying to compile under R 3.6.1, I think.

Upgrade R and Rtools to current versions.
