### ISSUE TITLE
Error when using sigPeak for bottom signal

### ISSUE THREAD

**Issue by jfsmenezes** [braverock/quantstrat#146]
### Description

Hi, it seems that a strategy with a signal `sigPeak()` with `direction="bottom"` yields and error when it is evaluated in a call of `applySignals`. I got the following error:

```r
Error in (function (label, data, column, direction = c("peak", "bottom"))  : 
  object 'ret_sig' not found
```
By looking inside the code, it seems the issue is with the `switch()` in `sigPeak`. Namely 

```r
 switch(direction, peak = {
           ret_sig <- Lag(data[, colNum], 2) < Lag(data[, colNum],
               1) & Lag(data[, colNum], 1) > data[, colNum]
       }, "bottom", valley = {
           ret_sig <- Lag(data[, colNum], 2) > Lag(data[, colNum], 
               1) & Lag(data[, colNum], 1) < data[, colNum]
       })
```

R understands "bottom" as an different option from "valley" in the switch. It just  outputs the word `"bottom"`. As a consequence the object `ret_sig` is never created and `return()` gives that error. A simple solution might just be to copy the code of the valley option to the bottom option.

```r
 switch(direction, peak = {
           ret_sig <- Lag(data[, colNum], 2) < Lag(data[, colNum],
               1) & Lag(data[, colNum], 1) > data[, colNum]
       }, bottom= {
           ret_sig <- Lag(data[, colNum], 2) > Lag(data[, colNum], 
               1) & Lag(data[, colNum], 1) < data[, colNum]
       }, valley = {
           ret_sig <- Lag(data[, colNum], 2) > Lag(data[, colNum], 
               1) & Lag(data[, colNum], 1) < data[, colNum]
       })
```
I tested the behavior of `switch` in both R.3.6.2 and R.4.1.2. In both cases the output is just the word `bottom`.

I think I solved the problem in my case (just changed the function), but thought you would like to know.

**Comment by jaymon0703** [comment]
Thank you for the report @jfsmenezes can you please share a minimally reproducible example, and perhaps submit a PR with your fix? I am not familiar with sigPeak() but can take a look when i get a moment.

**Comment by joshuaulrich** [comment]
There should be an equal sign after "bottom". Untested, but this should fix
it:

switch(direction,

    peak = { ... },

    bottom = ,

    valley = { ... })

**Comment by joshuaulrich** [comment]
Here's an example that errors:

```
library(quantstrat) 
x <- getSymbols("SPY", env = NULL) 
sp <- sigPeak("foo", data = x, column = "Close", direction = "bottom")
```

I just checked my proposed fix, and it works. I'll commit the patch.

**Comment by jaymon0703** [comment]
Thanks Josh!
