### ISSUE TITLE
[R-Forge #5298] QuantStrat issue with adding more than one indicator

### ISSUE THREAD

**Issue by joshuaulrich** [braverock/quantstrat#22]
Submitted by: Ilya Kipnis
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5298&group_id=316&atid=1269)

I'm doing this on Brian's server, so it may be an issue on my end, but...I added one more indicator to the Faber demo, and I'm attaching my 'broken' demo.

The difference is that I added another indicator, which is simply a copied and pasted version of the first, with the 10 changed to 15.

I'm not sure why this is happening...maybe I'm using some outdated technology, but, I just wanted to share this.

Here's my sessionInfo().

R version 3.0.2 (2013-09-25)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C         LC_TIME=C            LC_COLLATE=C  
 [5] LC_MONETARY=C        LC_MESSAGES=C        LC_PAPER=C           LC_NAME=C  
 [9] LC_ADDRESS=C         LC_TELEPHONE=C       LC_MEASUREMENT=C     LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] quantstrat_0.8.0           foreach_1.4.1              blotter_0.8.17  
 [4] PerformanceAnalytics_1.1.0 FinancialInstrument_1.1.9  quantmod_0.4-0  
 [7] Defaults_1.1-1             TTR_0.22-0.1               xts_0.9-7  
[10] zoo_1.7-10                

loaded via a namespace (and not attached):
[1] codetools_0.2-8 grid_3.0.2      iterators_1.0.6 lattice_0.20-24 tools_3.0.2  

Followups:

Date: 2014-02-12 16:25
Sender: Seth Wayland
The attached file throws an error for me at the applyStrategy call on line 122. The error is:Error in `colnames<-`(`*tmp*`, value = c('XLB.Close.SMA.15', 'XLB.Close.SMA.10.SMA10.SMA.15' :   length of 'dimnames' [2] not equal to array extentMy sessionInfo() output:R version 3.0.2 (2013-09-25)Platform: x86_64-apple-darwin10.8.0 (64-bit)locale:[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8attached base packages:[1] stats     graphics  grDevices utils     datasets  methods   base     other attached packages: [1] quantstrat_0.8.0           foreach_1.4.1              blotter_0.8.17             PerformanceAnalytics_1.1.2 [5] FinancialInstrument_1.1.9  quantmod_0.4-0             Defaults_1.1-1             TTR_0.22-0                 [9] xts_0.9-7                  zoo_1.7-10                loaded via a namespace (and not attached):[1] codetools_0.2-8 grid_3.0.2      iterators_1.0.6 lattice_0.20-24 tools_3.0.2   

Date: 2014-01-22 23:35
Sender: Joshua Ulrich
The attached file works for me. You didn't say what is broken.  My sessionInfo() output:R version 3.0.2 (2013-09-25)                                                                        Platform: x86_64-pc-linux-gnu (64-bit)                                                              locale: [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       attached base packages:[1] stats     graphics  grDevices utils     datasets  methods   base     other attached packages: [1] quantstrat_0.8.0           foreach_1.4.1              blotter_0.8.17             [4] PerformanceAnalytics_1.1.1 FinancialInstrument_1.1.9  quantmod_0.4-0             [7] Defaults_1.1-1             TTR_0.22-0.1               xts_0.9-7                 [10] zoo_1.7-10                 setwidth_1.0-3             colorout_1.0-1            loaded via a namespace (and not attached):[1] codetools_0.2-8 grid_3.0.2      iterators_1.0.6 lattice_0.20-24

**Comment by braverock** [comment]
Closing.  This error does not exist in current code.
