### ISSUE TITLE
[R-Forge #5814] store = TRUE not working for add.indicator and add.signal

### ISSUE THREAD

**Issue by joshuaulrich** [braverock/quantstrat#28]
Submitted by: Jonathan Owen
Assigned to: Joshua Ulrich
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5814&group_id=316&atid=1269)

Custom signal and indicator functions are not found when using apply.paramset, even though store=TRUE for both the add.indicator and add.signal calls.  The store logic within add.rule is working, so I've attached proposed fixes that also incorporate that logic into add.indicator and add.signal.  One other possible bug in the store logic for add.rule was also fixed.  If there is a better way to accomplish this, please let me know.

Followups:

Date: 2014-11-06 19:20
Sender: Jonathan Owen
I've attached diff files with proposed updates.

Date: 2014-07-24 16:36
Sender: Jonathan Owen
I've also noticed that a custom function passed to TxnFees during the add.rule call is not stored.  Since the TxnFees value is stored as a column in the orderbook, it doesn't look like the same functionality used for add.rule can be used to store the TxnFees function.  I've found that this mainly becomes a problem when apply.paramset is run in parallel, and one solution is to add an export parameter to apply.paramset that is passed to the .export parameter of the foreach call.

Date: 2014-07-24 12:19
Sender: Jonathan Owen
Slight correction to the proposed fix.  To be consistent with add.rule, add.signal and add.indicator should add a storefun = TRUE parameter instead of using the store parameter.

**Comment by braverock** [comment]
This is stale.  `store=TRUE` works.  Thanks to Jonathan Owen for drawing it to our attention.  We will open new issues if this or a similar problem recurs in the future.
