### ISSUE TITLE
sigPeak error: k must be a non-negative integer

### ISSUE THREAD

**Issue by joshuaulrich** [braverock/quantstrat#41]
In his [StackOverflow question](http://stackoverflow.com/q/37257151/271616) @wthielen showed that `sigPeak` throws an error for a simple use case.

```r
require(quantstrat)
data(sample_matrix)
x <- as.xts(sample_matrix)
sig <- sigPeak("label", x, "Close")
# Error in FUN(X[[i]], ...) : k must be a non-negative integer
```

This is caused by an extraneous call to `Lag` that can simply be removed.

**Comment by wthielen** [comment]
Thanks for the quick solution! Any idea when it will be in the next CRAN
release?

**Comment by joshuaulrich** [comment]
quantstrat is not currently on CRAN, and we don't have a timeline for putting it on CRAN.

**Comment by wthielen** [comment]
Ah, apologies, I meant R-Forge. I was wondering when I could update my
packages to get the latest updates.

**Comment by braverock** [comment]
We would like to automate builds, and potentially provide a repository, but that will only lead to source tarballs on github in the near term.

We are moving off R-Forge, in part because its build process is often broken.

**Comment by braverock** [comment]
I suggest using install_github() from devtools.

**Comment by wthielen** [comment]
Brian, thanks for the suggestion! I just did that, and see that the
infamous Lag line has been removed from the implementation of sigPeak in my
installation.
