### ISSUE TITLE
Encountering a problem when applying applyStrategy()

### ISSUE THREAD

**Issue by mattonline1** [braverock/quantstrat#57]
Could anybody point me in the right direction as to how I can go about fixing the following error. I encounter this error everytime I run `applyStrategy(strategy = stat........ etc.)`. I am no expert in R but is it something related to my computers clock/date? I am based in Europe using dd/mm/yyyy format.

Any guidance would be greatly appreciated.

```r
> applyStrategy(strategy = strat.name, portfolios = portofolio.name)`
Error in addTxn(Portfolio = portfolio, Symbol = symbol, TxnDate = txntime,  : 
  Transactions must be added in order. TxnDate (2010-01-04) is before last transaction in portfolio (2009-12-31) for EEM
In addition: Warning message:
In addTxn(Portfolio = portfolio, Symbol = symbol, TxnDate = txntime,  :
  Incompatible methods ("Ops.Date", "Ops.POSIXt") for "<"`
```

**Comment by joshuaulrich** [comment]
This is a bug in blotter https://github.com/braverock/blotter/issues/51, that I just pushed a fix for.  So I'm closing this, since it's not part of quantstrat and it's now fixed in blotter.
