### ISSUE TITLE
chart.forward - multiple blue equity curves

### ISSUE THREAD

**Issue by eustin** [braverock/quantstrat#61]
Output of session info can be found below. Issue can also be reproduced on Ubuntu 16.04.2 LTS.

Steps to reproduce:
- run demo macdWFA.R
- chart.forward('macdWFA.results.RData') results in 2 blue equity curves

Expected behaviour:
- only one blue equity curve to be displayed with the rest grey 

Observations when debugging chart.forward:
- n is set to 15 by n <- length(portfolios.st)
- PL.xts and Drawdows.xts are the objects plotted. They both have 16 columns.
- the vector passed to the plot function via the col argument is created like this: c("blue", rep("grey", n - 1). 
- this vector is one element short of 16 and results in recycling of colours.

sessioninfo ------------------------------

R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] quantstrat_0.10.2             blotter_0.9.1741             
 [3] PerformanceAnalytics_1.4.3541 FinancialInstrument_1.2.0    
 [5] quantmod_0.4-8                TTR_0.23-1                   
 [7] xts_0.10-0                    zoo_1.8-0                    
 [9] doRedis_1.2.0                 iterators_1.0.8              
[11] foreach_1.4.3                 rredis_1.7.0                 

loaded via a namespace (and not attached):
[1] parallel_3.3.3   tools_3.3.3      codetools_0.2-15 grid_3.3.3      
[5] lattice_0.20-34

**Comment by braverock** [comment]
John Kumar sent me an email on this on 2017-05-26:

> You might be aware that the chart.forward.training function does not
> actually highlight the correct plot, instead it highlights the first
> series of the PL.xts object. I think I have located the problem to
> this code:
> 
> p <- plot(PL.xts, col=c("blue", rep("grey", n)), main="Walk Forward
> Analysis")
> # set on=NA so it is drawn on a new panel
> p <- lines(Drawdowns.xts, col=c("blue", rep("grey", n)), on=NA,
> main="Drawdowns")
>   print(p)
> 
> which could be replaced with:
> p <- plot(PL.xts, col="grey", main="Walk Forward Analysis")
> p <- lines(PL.xts[,n+1],col="blue",on=1)
> # set on=NA so it is drawn on a new panel
> p <- lines(Drawdowns.xts, col="grey", on=NA, main="Drawdowns")
> p <- lines(Drawdowns.xts [,n+1],col="blue",on=2)
>   print(p)
> 
> to give desired functionality. Also  the xts object data.to.plot is
> not used anywhere as far as I can tell.
> 
> Chart.forward seems to have a similar problem but I haven't looked at
> it closely, yet.
You might be aware that the chart.forward.training function does not  
> actually highlight the correct plot, instead it highlights the first  
> series of the PL.xts object. I think I have located the problem to

> this code:

>   


> p <- plot(PL.xts, col=c("blue", rep("grey", n)), main="Walk Forward

> Analysis")

> # set on=NA so it is drawn on a new panel

> p <- lines(Drawdowns.xts, col=c("blue", rep("grey", n)), on=NA,

> main="Drawdowns")

>   print(p)

>   


> which could be replaced with:

> p <- plot(PL.xts, col="grey", main="Walk Forward Analysis")

> p <- lines(PL.xts[,n+1],col="blue",on=1)

> # set on=NA so it is drawn on a new panel

> p <- lines(Drawdowns.xts, col="grey", on=NA, main="Drawdowns")

> p <- lines(Drawdowns.xts [,n+1],col="blue",on=2)

>   print(p)

>   


> to give desired functionality. Also  the xts object data.to.plot is  
> not used anywhere as far as I can tell.

>   


> Chart.forward seems to have a similar problem but I haven't looked at  
> it closely, yet.

**Comment by braverock** [comment]
Between this report and John's email, I suspect the minimal patch is is likely to use color:

    `c(rep("grey", n ),"blue")`

if the optimal paramset is last, or 

    `c("blue", rep("grey", n ))` 

if the optimal paramset is first.

I'll take a look, thanks for the report.
