### ISSUE TITLE
add overfitting analysis and mitigation directly to quantstrat

### ISSUE THREAD

**Issue by braverock** [braverock/quantstrat#64]
Many methods have been suggested in the literature for detecting and mitigating overfitting.

Among them:
- White's reality check
- Harvey and Liu's Adjusted Sharpe Ratio
- Baley and Lopez de Prado's Deflated Sharpe Ratio

These functions should be added to *quantstrat*.

White's reality check is a bootstrap method, so it might end up in *blotter* with *txnsim* and *mcsim*, but we'll leave it here for now.

Both the adjusted Sharpe methods of Harvey and Liu and the Deflated Sharpe method require knowledge of the number of trials.  *quantstrat* will need to track number of trials in parameter optimization, walk forward, and changes to the strategy specification.

**Comment by braverock** [comment]
@jaymon0703 has identified 8 inputs to the Harvey and Liu code, and we need to sort out where *quantstrat* gets those inputs... here is a draft:

1. frequency

    periodicity(posPL)

2. number of observations
nrow(PosPL) 

    works, but has some problems, since the original strategy may have been run on higher frequency data than the portfolio was marked on, we'll need to document this and examine the impact it might have eventually, or maybe we should just add a slot to the strategy object for number of observations used in applyStrategy (though we need to be careful not to overwrite in parameter opt or walk.forward)

    for daily it is simple, since you will trade and mark the book on the same frequency

    for intraday strategies it is more complex, since you may trade on tick but mark the book every minute, 5 minutes, 10-min or hour.  sometimes you might even mark the book daily

    marking an intraday trade on minutes isn't  too bad, 1440 observations per day + one for every trade, and periodicity will correctly detect minute data

    @jaymon0703 pointed out on Hangouts that Harvey and Liu use daily data as their highest frequency, so we may have some work to do to measure the impact of higher frequency data on the estimation

3. initial Sharpe ratio

    from tradeStats

4. is Sharpe ratio annualized

    it can be, from tradeStats again

5. has Sharpe ratio been corrected for autocorrelation

    not in any of the *quantstrat* stuff, so 6 should correct

 6. A/C corrected Sharpe ratio (assuming 5 is NO), 

    autocorrelation can be calculated from the summary slot of the audit environment for paramsets or WFA, or from PosPL of multiple strategies if multiple portfolios are explicitly used.

7. assumed number of tests

    $trials slot of the strategy , or number of distinct strategies passed in

8. level of correlation among strategy returns

    can be calculated pretty easily from the portfolios, or the summary slot of WFA or paramset testing

**Comment by jaymon0703** [comment]
In addition to replicating the model developed by Harvey & Liu in R and in the interest of breaking down the model into logical components, we could look to implementing the following:

1. Output relevant charts such as a random sample of the exponential distribution of t-ratios, stored in t_sample as a result from the call to sample_random_multests(). Harvey & Liu make some distribution assumptions ("...and the Cross-Section of Expected Returns", Section 5.1 p.27) for the strategy returns of factors. In particular, they assume an exponential distribution of these returns based on the intuition that profitable strategies are less likely to exist hence appropriateness of a monotonically decreasing probability density function.

2. It may also be useful, in the context of using a Haircut Sharpe Ratio function in quantstrat, to chart the non-linear relationship for haircut adjustments based on the initial Sharpe ratio for the relevant strategies. Harvey & Liu mention on p.1 of _Backtesting_ that in their multiple testing model the highest Sharpe ratios are only moderately penalized whilst marginal ones more heavily so. Their economic explanation for this is that strategies with higher Sharpe ratios are more likely true discoveries, and the industry standard of 50% haircuts would be "too punitive" in these cases.

There could be more examples to add which would augment the great work of Harvey & Liu in R.

**Comment by braverock** [comment]
should probably do some housekeeping before merging:

- return data structures that are usable in output or further analysis
- supply print methods where we don't already have them
- add examples and demos

I may take one more look at White's Reality Test too.  It would probably be good to have it in *quantstrat* or *blotter*
