### ISSUE TITLE
multi instrument on single strategy

### ISSUE THREAD

**Issue by willwill4000** [braverock/quantstrat#70]
Is it possible to run a single strategy on multiple instruments?

I have a momentum rotation strategy that I like to run but it seems apply.strategy only runs one instrument at a time.

I have a basket of stocks where I like to choose only one stock to allocate money in at any given time when my indicators go off for that particular stock.

**Comment by braverock** [comment]
Yes, it is possible.  Use a rebalance rule to set your 'only one stock'.  Set max position for everything else to zero, except for your preferred instrument.

We've discussed adding formal support for cross-asset filters, so if you're particularly interested in that idea, send me an email.

Also, github issues are really for reporting problems, not asking for help.
