### ISSUE TITLE
Error in .firstCross(dindex, curIndex, "gt") : object 'C_firstCross' not found

### ISSUE THREAD

**Issue by swapsha** [braverock/quantstrat#76]
Hi ,

 I am getting the following error while applying rules and applying strategy
Error in .firstCross(dindex, curIndex, "gt") : object 'C_firstCross' not found

```r
add.rule(strategy = strategy.st, name="ruleSignal", arguments = list(
    sigcol = "RSI_gt_50", sigval = TRUE, orderqty = 1, ordertype = "market", 
    orderside = "long", replace = FALSE), type = "enter",label='enter long')
add.rule(strategy.st,name='ruleSignal', 
    		 arguments = list(sigcol="RSI_lt_50",
    				              sigval=TRUE, 
    						          orderqty='all', 
    						          ordertype='market', 
    						          orderside='long', 
    						          prefer="Low",
    						          replace=FALSE),
         type='exit',
    		 label='exit long'
)
applyRules(strategy=strategy.st, portfolio = portfolio.st,mktdata=mktdata2,symbol="NSE")
```

Could you please help me in fixing this

Thanks

**Comment by joshuaulrich** [comment]
Something is wrong with your quantstrat installation.  You either made changes to the source code yourself, or you installed quantstrat via RStudio and/or using devtools when quantstrat was already loaded and attached to a running R session.

**Comment by swapsha** [comment]
Yes, Packages installation issue.
Reinstalled and its working fine
Thanks
