### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by richierocks** [braverock/quantstrat#87]
Having a `README.md` that includes a description of the package's purpose and some installation instructions is really helpful.

(In particular, many DataCamp students want to know how to install this package after taking the financial trading course.)

`usethis::use_readme_md()` and `usethis::use_readme_rmd()`  will give you a template that forms a nice starting point for the contents.

**Comment by jaymon0703** [comment]
Hi Richard

I have been meaning to add a README, similar to something i added to
blotter a few months back. Please have a look and let me know your
thoughts, i can follow the same template. Unless of course Brian has other
ideas.

Regards
Jasen

**Comment by richierocks** [comment]
@jaymon0703 The blotter README is a good start. I have some opinions: 

- You probably don't need to list dependencies and contributors. Unless you use a `README.Rmd` file and autogenerate dependencies and contributors from the DESCRIPTION file, it's easy for the information to get out of date and be more confusing than helpful.
- It's a really good idea to add examples of the most important functions. I'm quite proud of the case study approach I used in my [yelp](https://github.com/richierocks/yelp) pacakge.
- It's also nice to have links to resources for the package. I think [ggplot2](https://github.com/tidyverse/ggplot2) does a great job of this.

**Comment by jaymon0703** [comment]
thanks @richierocks i have added a README similar to blotter, and will take a look at your suggestions and update accordingly

**Comment by jaymon0703** [comment]
@richierocks appreciate your thoughts on the README before we close. Thanks to @joshuaulrich and @braverock for getting travis.ci integration passing.
