### ISSUE TITLE
Error "Walk.forward()":.getPortfolio(portfolio) error in WFA 

### ISSUE THREAD

**Issue by N0talent** [braverock/quantstrat#89]
when run the Demo "/demo/macdWFA.R" and get following Error:
`Error in .getPortfolio(portfolio) : 
  Portfolio wf.macd not found, use initPortf() to create a new portfolio`

before `walk.forward()` is run, `.blotter` has "portfolio.wf.macd" stored. After I run walkforward() and the error is been thrown, .blotter replaced "portfolio.wf.macd" with "portfolio.wf.macd.159"

**Comment by N0talent** [comment]
setting `saveenv=TRUE` in `walk.forward()`resolved the issue for me. Is the Demo Wrong or is it a Bug in `walk.forward()`?

**Comment by braverock** [comment]
@N0talent , thanks for the report.

In May of 2018, I made a number of changes to the parameter optimization and `walk.forward` code.

One of those was to make saving the entire set of environments `FALSE` by default, as this uses a huge amount of RAM, and violates CRAN policies on writing to the user's environment without being explicitly told to.

In this case, I'd argue that we should update the demo.  

Using `saveenv=TRUE` here is an easy fix, and doesn't use that much RAM, as this is neither large data nor a lot of parameters.  We might need to think about whether that sends a bad message for a larger test.  Thoughts?

**Comment by N0talent** [comment]
Sounds good. 
Knowing the reasons why the changes were made to `apply.paramset()`, I have a follow-up question:
How would i need to configure `walk.forward()` in the Case that the i do have a Large Dataset, and Large Parameter optimization?

**Comment by braverock** [comment]
@N0talent : Take a look at the vignette presentation that I added to the repository alongside those changes.

[quantstrat-RFinance-2018.Rmd](https://github.com/braverock/quantstrat/blob/master/vignettes/quantstrat-RFinance-2018.Rmd)

**Comment by QuantDevHacks** [comment]
Have been encountering the same error as @N0talent described, with a simple example that ran fine a year ago when I was teaching walk forward analysis using quantstrat.  Tried putting the `saveenv=TRUE` setting as a parameter inside `walk.forward(.)` as noted above, but still getting the same error.  I'm running quantstrat v0.15.6 on R v3.5.3.  Have there been any changes since those made in May last year that might be causing this, or might there be an additional workaround required?  I can send you the full script if you wish.  Was going to show this example this week (in this year's class), but hit this issue when testing it out tonight.

**Comment by jaymon0703** [comment]
Hi, yes there have been a host of changes since May last year. The latest version is 0.15.7 although unlikely to impact your test. Feel free to send through the script and I will investigate?

**Comment by QuantDevHacks** [comment]
Thanks @jaymon0703.  Here you go:

`library(quantstrat)

stock.st = c("SPY")   # aka symbol (in previous examples)
currency("USD")
stock(stock.st, currency="USD",multiplier=1)
Sys.setenv(TZ="UTC") # set time zone
initDate = '2007-12-31'
startDate = '2008-01-01'
endDate = '2018-04-30'
initEq=1e6
nShs = 500    # ~ $135000 per trade
getSymbols(stock.st,from=startDate,to=endDate,index.class="POSIXct",adjust=T)

strat.st <- "bbands"
rm.strat(strat.st)
strategy(strat.st, store=TRUE)
add.indicator(strat.st, name = "BBands",
              arguments = list(HLC = quote(HLC(mktdata)), maType='SMA'), label='BBands')

add.signal(strat.st, name="sigCrossover",
           arguments=list(columns=c("Close","up"),relationship="gt"),
           label="Cl.gt.UpperBand")

add.signal(strat.st, name="sigCrossover",
           arguments=list(columns=c("Close","dn"),relationship="lt"),
           label="Cl.lt.LowerBand")

add.signal(strat.st, name="sigCrossover",
           arguments=list(columns=c("High","Low","mavg"),relationship="op"),
           label="Cross.Mid")

add.rule(strategy = strat.st, name='ruleSignal',
         arguments=list(sigcol="Cl.gt.UpperBand",sigval=TRUE, orderqty=-nShs,
                        ordertype='market', orderside=NULL, threshold=NULL),
         type='enter', label = "Enter.Short")

add.rule(strategy = strat.st, name='ruleSignal',
         arguments=list(sigcol="Cl.lt.LowerBand",sigval=TRUE, orderqty=nShs,
                        ordertype='market', orderside=NULL, threshold=NULL),
         type='enter', label = "Enter.Long")

add.rule(strategy = strat.st, name='ruleSignal',
         arguments=list(sigcol="Cross.Mid",sigval=TRUE, orderqty= 'all',
                        ordertype='market', orderside=NULL, threshold=NULL),
         type='exit', label = "Exit.All")

add.distribution(strat.st,
                 paramset.label = 'BBOPT',
                 component.type = 'indicator',
                 component.label = 'BBands',
                 variable = list(n = seq(10,30,by=10)),
                 label = 'n'
)

add.distribution(strat.st,
                 paramset.label = 'BBOPT',
                 component.type = 'indicator',
                 component.label = 'BBands',
                 variable = list(sd = seq(1,3,by=1)),
                 label = 'sd'
)


# Portfolio and Account names are "opt".
rm.strat("opt")
initPortf(name="opt", stock.st, initDate=initDate)
initAcct(name="opt", portfolios="opt",
         initDate=initDate, initEq=initEq)
initOrders(portfolio="opt", initDate=initDate)

results <- walk.forward(
  strategy.st=strat.st,
  paramset.label='BBOPT',
  portfolio.st="opt",
  account.st="opt",
  period='years',
  k.training=4,
  k.testing=1,
  nsamples=0,
  audit.prefix='wfaBB',
  anchored=FALSE,
  verbose=FALSE,
  saveenv=TRUE
)`

Error returned:
`Error in .getPortfolio(paste0("orig.", orig.portfolio.st)) : 
  Portfolio orig.opt not found, use initPortf() to create a new portfolio`

**Comment by jaymon0703** [comment]
Thanks. I will take a look in several hours, but I wonder if removing the strategy object before your call to walk.forward may be the issue?

**Comment by QuantDevHacks** [comment]
Thanks!

The `rm.strat("opt")` command is there to remove the portfolio and account settings from the previous run so that they can be re-initialized.  The strategy ("bbands") is actually set before the indicator.  This is the same script that ran OK for my class last year, and it is basically a simplified version of [Guy Yollin's example](https://4310b1a9-a-a8fb2076-s-sites.googlegroups.com/a/r-programming.org/home/files/WFA.pdf) that has been a commonly cited example on the internet (I essentially did the same thing but with a simplified Bollinger Bands strategy).  Also, I guess I didn't mention that the WFA does start, but stops after one combination and yields the error; viz,

```
...
[1] "2011-08-05 00:00:00 SPY 500 @ 104.634776577228"
[1] "2011-08-09 00:00:00 SPY 500 @ 102.369201044792"
[1] "2011-08-31 00:00:00 SPY -1000 @ 106.499519361297"
[1] "=== testing param.combo 6 on 2012-01-03/2012-12-31"
   n sd
6 30  2
Error in .getPortfolio(paste0("orig.", orig.portfolio.st)) : 
  Portfolio orig.opt not found, use initPortf() to create a new portfolio
```

**Comment by jaymon0703** [comment]
Your script seems to work fine for me @QuantDevHacks. The only difference is i am on 0.15.7, although the bump in version from 0.15.6 to 0.15.7 was for an intraday subset in applyRules() which is not affected with your walk.forward script. 

![image](https://user-images.githubusercontent.com/4340156/57770381-76556200-7710-11e9-83d7-76fd05ac59ae.png)

**Comment by QuantDevHacks** [comment]
The update seemed to do the trick.  Just one side note, however:  I updated blotter first -- in which there definitely were changes -- but when I updated quantstrat, a message returned saying I was now on the latest version.  Thanks again for helping me out on this!

**Comment by jaymon0703** [comment]
Great, thanks for letting us know. Hopefully you can still use it in your lecture!
