### ISSUE TITLE
demo/rsi.R possible bug?

### ISSUE THREAD

**Issue by ssh352** [braverock/quantstrat#95]
<img width="1439" alt="Screen Shot 2019-03-26 at 5 10 22 PM" src="https://user-images.githubusercontent.com/41779116/54984565-11bc3780-4fea-11e9-817d-0c731402ec39.png">

Is it intended to go long when rsi >70? and short when rsi < 30?

**Comment by jaymon0703** [comment]
hi @ssh352 the rules with orderqty='all' are the exit rules, so the example you highlighted is a rule stipulating to close a long position when sigcol "RSI.gt.70" is TRUE.

**Comment by ssh352** [comment]
@jaymon0703 Thank you, so as you said, orderside='long' in an exit rule means flattening out a long position. The action is actually selling so I thought it should be orderside='short', my mistake.

A related question, orderqty can be negative or positive from the demos, so that means a sell rule should always have a negative orderqty?

**Comment by jaymon0703** [comment]
@ssh352 `orderside='NULL'` is also an acceptable parameter value. May be worthwhile reviewing the docs for the `ruleSignal` function if you have not already? 

`If orderside is NULL, the function will attempt to calculate the side from the current position (if any), the order quantity, and the order type.`

sell rule should always have a negative quantity indeed

**Comment by jaymon0703** [comment]
@ssh352 can we close the issue?
