### ISSUE TITLE
question: applyStrategy how to disable printing of transactions

### ISSUE THREAD

**Issue by ssh352** [braverock/quantstrat#96]
<img width="626" alt="Screen Shot 2019-04-08 at 9 22 09 PM" src="https://user-images.githubusercontent.com/41779116/55727428-91afbc00-5a44-11e9-8c70-560047fdc87d.png">

I have some trouble finding how these transaction lines are generated in the code. And I'd like to disable it for long simulations. Thank you.

**Comment by braverock** [comment]
`verbose=FALSE`

**Comment by ssh352** [comment]
Thanks, I found it from your hint, it is actually from blotter code addTxn
