### ISSUE TITLE
[audit.prefix].results.RData file not produced when running walk.forward(.)

### ISSUE THREAD

**Issue by QuantDevHacks** [braverock/quantstrat#99]
When running` walk.forward(.)`, the `[audit.prefix].results.RData` file is not produced in the Documents folder in Win10.  The in-sample RData files were not generated either. This was working OK in the same script last year at this time (I use quantstrat in a course I teach during the spring of each year).

I also checked Issue #56, and I verified that the conditions noted there are set in the parameters, specifically `audit.prefix = TRUE` and `include.insamples=TRUE` (the latter is the default setting):

```
results <- walk.forward(
  strategy.st=strat.st,
  paramset.label='BBOPT',
  portfolio.st="opt",
  account.st="opt",
  period='years',
  k.training=3,
  k.testing=1,
  nsamples=0,
  audit.prefix='wfa',
  anchored=FALSE,
  verbose=TRUE)
```

The `results` and `results$audit` environment are generated, however.  In a related remark, the documentation for `chart.forward(.)`, it says that in place of the `[audit.prefix].results.RData` argument for `audit.filename`,  _[a]lternately, an audit environment provided by the output of `walk.forward`_.   As the RData file was not produced, I tried using the environment argument instead, but this resulted in an error; viz,

```chart.forward(audit.filename = results$audit, portfolio.st = 'opt')```

results in the error

```
Error in if (!grepl("portfolio\\.", pname)) Portfolio <- uppressWarnings(try(get(paste("portfolio",  : argument is of length zero
```
The upshot is that I can find no way to check the graphical results of my out of sample testing.  Has something changed over the last year?  A new setting somewhere that might be necessary?  Something else going on?

Below is the entire repro code:
```
library(quantstrat)

stock.st = c("SPY")
currency("USD")
stock(stock.st, currency="USD",multiplier=1)
Sys.setenv(TZ="UTC") 
initDate = '2011-12-31'
startDate = '2012-01-01'
endDate = '2017-12-31'    
initEq=1e6
tradeSize = initEq/10
getSymbols(stock.st,from=startDate,to=endDate,index.class="POSIXct",adjust=T)

strat.st <- "bbands"
rm.strat(strat.st)
strategy(strat.st, store=TRUE)

add.indicator(strat.st, name = "BBands",
              arguments = list(HLC = quote(HLC(mktdata)), maType='SMA'), label='BBands')

add.signal(strat.st, name="sigCrossover",
           arguments=list(columns=c("Close","up"),relationship="gt"),
           label="Cl.gt.UpperBand")

add.signal(strat.st, name="sigCrossover",
           arguments=list(columns=c("Close","dn"),relationship="lt"),
           label="Cl.lt.LowerBand")

add.signal(strat.st, name="sigCrossover",
           arguments=list(columns=c("High","Low","mavg"),relationship="op"),
           label="Cross.Mid")

add.rule(strategy = strat.st, name='ruleSignal',
         arguments=list(sigcol="Cl.gt.UpperBand",sigval=TRUE, orderqty=-100,
                        ordertype='market', orderside=NULL, threshold=NULL),
         type='enter', label = "Enter.Short")

add.rule(strategy = strat.st, name='ruleSignal',
         arguments=list(sigcol="Cl.lt.LowerBand",sigval=TRUE, orderqty=100,
                        ordertype='market', orderside=NULL, threshold=NULL),
         type='enter', label = "Enter.Long")

add.rule(strategy = strat.st, name='ruleSignal',
         arguments=list(sigcol="Cross.Mid",sigval=TRUE, orderqty= 'all',
                        ordertype='market', orderside=NULL, threshold=NULL),
         type='exit', label = "Exit.All")

add.distribution(strat.st,
                 paramset.label = 'BBOPT',
                 component.type = 'indicator',
                 component.label = 'BBands',
                 variable = list(n = seq(10,30,by=10)),     # 2 steps total
                 label = 'n'
)

add.distribution(strat.st,
                 paramset.label = 'BBOPT',
                 component.type = 'indicator',
                 component.label = 'BBands',
                 variable = list(sd = seq(1,3,by=1)),    # 2 steps total
                 label = 'sd'
)

# Portfolio and Account names are "opt"
rm.strat("opt")
initPortf(name="opt", stock.st, initDate=initDate)
initAcct(name="opt", portfolios="opt",
         initDate=initDate, initEq=initEq)
initOrders(portfolio="opt", initDate=initDate)

results <- walk.forward(
  strategy.st=strat.st,
  paramset.label='BBOPT',
  portfolio.st="opt",
  account.st="opt",
  period='years',
  k.training=3,
  k.testing=1,
  nsamples=0,
  audit.prefix='wfa',
  anchored=FALSE,
  verbose=TRUE)
```

**Comment by jaymon0703** [comment]
hi @QuantDevHacks i will have a look today

**Comment by jaymon0703** [comment]
ok @QuantDevHacks, what changed a year ago was Brian changed the default for `savewf` to FALSE in this commit - https://github.com/braverock/quantstrat/commit/f8afbac0599b8829167bd7b85ad0c9196516cf91

specifying `savewf=TRUE` should resolve your issue?

**Comment by QuantDevHacks** [comment]
Thanks @jaymon0703; that does indeed produce the files.  However, I noticed there is no `wfa.results.RData` file present; instead, there is the file `wfa.SPY.20140102T000000.20161230T000000.Results.RData`.

Attempting to plot the results:
`chart.forward("wfa.SPY.20140102T000000.20161230T000000.Results.RData")`, however, results in the error
```
Error in chart.forward("wfa.SPY.20140102T000000.20161230T000000.Results.RData") : 
  'audit.filename' should match pattern:
  [audit.prefix].results.RData
```
Tried naively changing the file name and running `chart.forward('wfa.results.RData')`, but now this results in this error:  
```
Error in as.environment(pos) : using 'as.environment(NULL)' is defunct
```
So, the files are now present, but I'm still not able to plot the results as I could last year.

**Comment by jaymon0703** [comment]
Right, so a year ago there was a [commit](https://github.com/braverock/quantstrat/commit/f9321b52f6e7441c87e1e37a6bb5b63478c844ca) which made some enhancements to `walk.forward` making it more efficient via use of environments and vectorization. One of the changes was to add the `time.range` to the filename of the RData object. However, it seems the `grepl()` in `chart.forward` was not updated. I will chat to @braverock to make sure, before making any changes to `chart.forward()` for the updated filename.

**Comment by QuantDevHacks** [comment]
@jaymon0703  - Will look forward to your follow-up on this.  Thanks very much!

**Comment by jaymon0703** [comment]
We should have a fix committed by the end of the weekend. Thanks for the reporting.

**Comment by jaymon0703** [comment]
Hi @QuantDevHacks please upgrade to 0.15.8 and re-test with loading filename into chart.forward()?

So `chart.forward("wfa.SPY.20140102T000000.20161230T000000.Results.RData")` should work as expected now?

Also worth noting that the alternative value for `audit.filename` is "results", which if existing in your R session (which it is after running your script above or loading the saved file into a clean environment), and calling `chart.forward(results)` would have given you the same chart you were looking for.

**Comment by QuantDevHacks** [comment]
Thanks @jaymon0703; I am now able to generate plots using either form.  However, one thing that seemed strange is in the `chart.forward(results)` case, the blue line plot in the period up to the first test period (presumably this should be the optimized strategy over the 1st training period) starts at a level of about 2500 on the vertical axis, while all the gray lines start at 0.  When using `chart.forward.training(.)` on the first training period, however, the blue line starts at 0, as would be expected.  Should I open a separate issue for this?

Thanks again for the quick turnaround.

**Comment by jaymon0703** [comment]
Great thanks for the feedback @QuantDevHacks. I will close this issue.

Regarding the plot output, i am fairly new to the walk.forward function and the plot output. Reading through the code its clear we add the mean PL of all simulations as at the start of the first test window to the starting point of the optimized strategy (with a comment about training portfolios having a headstart).

![image](https://user-images.githubusercontent.com/4340156/57980189-fb4dbd80-7a27-11e9-9d04-c8900f193466.png)

I would say please create a separate issue for this, as i am due to clarify my understanding of the plot output with @braverock later today and will update the new issue accordingly.
